# Generated by Django 5.1.4 on 2024-12-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Pytronumic', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255, unique=True)),
                ('Role', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
